services:
  - type: web
    name: digitalkawach-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: GROQ_API_KEY
        sync: false
